apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: product
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser02-product:v1
          ports:
            - containerPort: 8080
          resources:
            requests: 
              #memory: "20Mi" 
              cpu: "200m" # 1/5 core
            limits:
              #memory: "40Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: '/products'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/products'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
